server:
  port: 6010

service:
  message:  Order MS Web service is up

spring:
  data:
    cassandra:
      contact-points: 10.20.1.174
      port: 9042
      keyspace-name: order
      username: flashex
      password: flashex
