server:
  port: 6030

service:
  message: Hi, trip tracking service is up

spring:
  data:
    cassandra:
      contact-points: 10.20.1.174
      port: 9042
      keyspace-name: triptracking
      username: flashex
      password: flashex
