server: 
  port: 5020

spring:
  kafka: 
    bootstrap-servers: 10.20.1.174:9092
  data:
    cassandra:
      contact-points: 10.20.1.174
      port: 9042
      keyspace-name: tripplanning
      username: flashex
      password: flashex
